version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@db:5432/boekhoud
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-geheim-veranderen-in-productie}
      - FLASK_ENV=${FLASK_ENV:-production}
      - UPLOAD_FOLDER=/app/static/uploads
      - MAX_CONTENT_LENGTH=1073741824  # 1GB in bytes
    volumes:
      - ./:/app
      - uploads_data:/app/static/uploads
      - tmp_data:/tmp
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:5000 --timeout 600 --workers 4 --threads 2 main:app

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=boekhoud
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Postgres configuratie voor grotere data en verbindingen
    command: >
      postgres
        -c max_connections=200
        -c shared_buffers=256MB
        -c effective_cache_size=512MB
        -c work_mem=16MB
        -c maintenance_work_mem=64MB
        -c max_wal_size=1GB

volumes:
  postgres_data:
    # Data volume voor databasegegevens
  uploads_data:
    # Data volume voor geüploade bestanden
  tmp_data:
    # Tijdelijke data volume voor uploads

# Netwerk configuratie
networks:
  default:
    driver: bridge