version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/facturatie
      - SESSION_SECRET=mijngeheimesessiekey # Verander dit in productie
      - MS_GRAPH_CLIENT_ID=${MS_GRAPH_CLIENT_ID}
      - MS_GRAPH_CLIENT_SECRET=${MS_GRAPH_CLIENT_SECRET}
      - MS_GRAPH_TENANT_ID=${MS_GRAPH_TENANT_ID}
      - MS_GRAPH_SENDER_EMAIL=${MS_GRAPH_SENDER_EMAIL}
    volumes:
      - ./static/uploads:/app/static/uploads
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=facturatie
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local